blockExoticSubdeps: true

minimumReleaseAge: 4320

# These are dependencies that run the postinstall script
# Only add dependencies to this if they have been vetted for security
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

trustPolicy: true
