// This file is auto-generated from template-parameters.json
// Do not edit manually - run 'yarn build' to regenerate

export interface GeneratedGtmParameters {
  type?: 'init' | 'track' | 'identify' | 'setUserId' | 'setGroup' | 'groupIdentify' | 'revenue' | 'flush' | 'setDeviceId' | 'setSessionId' | 'reset' | 'setOptOut';
  apiKey: string;
  setOptOut?: boolean;
  setSessionId: string;
  setUserId?: string;
  groupType: string;
  groupName: string;
  setDeviceId: string;
  eventType: string;
  eventProperties?: Array<{name: string; value: string}>;
  eventPropertiesObject?: Record<string, string>;
  trackTimestamp?: string;
  trackWithGroups?: boolean;
  trackEventGroups?: Array<{eventGroupType: string; eventGroupName: string}>;
  revenueFromVariable?: boolean;
  revenueVariable?: Record<string, string>;
  revenueId: string;
  revenuePrice: string;
  revenueQuantity?: string;
  revenue?: string;
  revenueType?: string;
  revenueCurrency?: string;
  revenueReceipt?: string;
  revenueReceiptSignature?: string;
  revenueEventProperties?: Array<{name: string; value: string}>;
  identifyGroupType: string;
  identifyGroupName: string;
  userPropertyOperations?: Array<{command: 'set' | 'setOnce' | 'add' | 'append' | 'prepend' | 'remove' | 'preInsert' | 'postInsert' | 'clearAll' | 'unset'; userProperty: string; value: string}>;
  userPropertyOperationsObject?: Record<string, string>;
  defaultEventTracking?: boolean;
  detAttribution?: boolean;
  attributionInitialEmptyValue?: string;
  attributionExcludeReferrers?: string;
  attributionExcludeReferrersRegex?: string;
  attributionResetSession?: boolean;
  detPageView?: boolean;
  pageViewLegacy?: boolean;
  pageViewType?: string;
  pageHistoryTracking?: 'all' | 'path';
  detSession?: boolean;
  detFormInteraction?: boolean;
  detFileDownload?: boolean;
  autocaptureElementInteractions?: boolean;
  elementInteractionsCssSelectorAllowlist?: string;
  elementInteractionsActionClickAllowlist?: string;
  elementInteractionsPageUrlAllowlistString?: string;
  elementInteractionsPageUrlAllowlistRegex?: string;
  elementInteractionsDataAttributePrefixString?: string;
  elementInteractionsDataAttributePrefixRegex?: string;
  autocaptureFrustrationInteractions?: boolean;
  rageClicksCssSelectorAllowlist?: string;
  deadClicksCssSelectorAllowlist?: string;
  autocaptureNetworkTracking?: boolean;
  networkTrackingIgnoreAmplitudeRequests?: boolean;
  networkTrackingIgnoreHosts?: string;
  networkTrackingCaptureRules?: Array<{urls?: string; methods?: string; statusCodeRange?: string; urlsRegex?: string; responseHeaders?: string; responseBody?: string; requestHeaders?: string; requestBody?: string}>;
  autocaptureWebVitals?: boolean;
  pageUrlEnrichment?: boolean;
  euData?: boolean;
  initUserId?: string;
  initOptions?: 'manual';
  initManualOptions?: Array<{key: 'flushIntervalMillis' | 'flushMaxRetries' | 'flushQueueSize' | 'logLevel' | 'minIdLength' | 'serverUrl' | 'useBatch' | 'appVersion' | 'deviceId' | 'identityStorage' | 'partnerId' | 'sessionTimeout' | 'userId' | 'optOut' | 'transport'; value: string}>;
  initTrackingOptions?: Array<{key: 'ipAddress' | 'language' | 'platform'; value: string}>;
  initCookieOptions?: Array<{key: 'domain' | 'expiration' | 'sameSite' | 'secure' | 'upgrade'; value: string}>;
  userAgentEnrichment?: boolean;
  osName?: boolean;
  osVersion?: boolean;
  deviceManufacturer?: boolean;
  deviceModel?: boolean;
  sessionReplay?: boolean;
  guidesSurveys?: boolean;
  instanceName?: string;
}