// This file is auto-generated from template-parameters.json
// Do not edit manually - run 'yarn build' to regenerate

export interface GeneratedGtmParameters {
  type?: 'init' | 'track' | 'identify' | 'setUserId' | 'setGroup' | 'groupIdentify' | 'revenue' | 'flush' | 'setDeviceId' | 'setSessionId' | 'reset' | 'setOptOut';
  apiKey: string;
  setOptOut?: boolean;
  setSessionId: string;
  setUserId?: string;
  setGroup?: {groupType?: string; groupName?: string};
  groupType: string;
  groupName: string;
  setDeviceId: string;
  trackGroup?: {eventType?: string; eventProperties?: Array<{name: string; value: string}>; eventPropertiesObject?: Record<string, string>; trackTimestamp?: string; trackWithGroups?: boolean; trackEventGroups?: Array<{eventGroupType: string; eventGroupName: string}>};
  eventType: string;
  eventProperties?: Array<{name: string; value: string}>;
  eventPropertiesObject?: Record<string, string>;
  trackTimestamp?: string;
  trackWithGroups?: boolean;
  trackEventGroups?: Array<{eventGroupType: string; eventGroupName: string}>;
  revenueGroup?: {revenueFromVariable?: boolean; revenueInput?: {revenueId?: string; revenuePrice?: string; revenueQuantity?: string; revenue?: string; revenueType?: string; revenueCurrency?: string; revenueReceipt?: string; revenueReceiptSignature?: string; revenueEventProperties?: Array<{name: string; value: string}>}};
  revenueFromVariable?: boolean;
  revenueVariable?: Record<string, string>;
  revenueInput?: {revenueId?: string; revenuePrice?: string; revenueQuantity?: string; revenue?: string; revenueType?: string; revenueCurrency?: string; revenueReceipt?: string; revenueReceiptSignature?: string; revenueEventProperties?: Array<{name: string; value: string}>};
  revenueId: string;
  revenuePrice: string;
  revenueQuantity?: string;
  revenue?: string;
  revenueType?: string;
  revenueCurrency?: string;
  revenueReceipt?: string;
  revenueReceiptSignature?: string;
  revenueEventProperties?: Array<{name: string; value: string}>;
  identifyGroup?: {identifyGroupType?: string; identifyGroupName?: string; userPropertyOperations?: Array<{command: 'set' | 'setOnce' | 'add' | 'append' | 'prepend' | 'remove' | 'preInsert' | 'postInsert' | 'clearAll' | 'unset'; userProperty: string; value: string}>; userPropertyOperationsObject?: Record<string, string>};
  identifyGroupType: string;
  identifyGroupName: string;
  userPropertyOperations?: Array<{command: 'set' | 'setOnce' | 'add' | 'append' | 'prepend' | 'remove' | 'preInsert' | 'postInsert' | 'clearAll' | 'unset'; userProperty: string; value: string}>;
  userPropertyOperationsObject?: Record<string, string>;
  initGroup?: {defaultEventTracking?: boolean; euData?: boolean; initUserId?: string; initOptions?: 'manual'; initManualOptions?: Array<{key: 'flushIntervalMillis' | 'flushMaxRetries' | 'flushQueueSize' | 'logLevel' | 'minIdLength' | 'serverUrl' | 'useBatch' | 'appVersion' | 'deviceId' | 'identityStorage' | 'partnerId' | 'sessionTimeout' | 'userId' | 'optOut' | 'transport'; value: string}>; initTrackingOptions?: Array<{key: 'ipAddress' | 'language' | 'platform'; value: string}>; initCookieOptions?: Array<{key: 'domain' | 'expiration' | 'sameSite' | 'secure' | 'upgrade'; value: string}>; userAgentEnrichment?: boolean; sessionReplay?: boolean; guidesSurveys?: boolean};
  defaultEventTracking?: boolean;
  defaultEventTrackingOptions?: {detAttribution?: boolean; detPageView?: boolean; detSession?: boolean; detFormInteraction?: boolean; detFileDownload?: boolean; autocaptureElementInteractions?: boolean; autocaptureFrustrationInteractions?: boolean; autocaptureNetworkTracking?: boolean};
  detAttribution?: boolean;
  attributionOptions?: {attributionInitialEmptyValue?: string; attributionExcludeReferrers?: string; attributionExcludeReferrersRegex?: string; attributionResetSession?: boolean};
  attributionInitialEmptyValue?: string;
  attributionExcludeReferrers?: string;
  attributionExcludeReferrersRegex?: string;
  attributionResetSession?: boolean;
  detPageView?: boolean;
  pageViewOptions?: {pageViewLegacy?: boolean; pageViewType?: string; pageHistoryTracking?: 'all' | 'path'};
  pageViewLegacy?: boolean;
  pageViewType?: string;
  pageHistoryTracking?: 'all' | 'path';
  detSession?: boolean;
  detFormInteraction?: boolean;
  detFileDownload?: boolean;
  autocaptureElementInteractions?: boolean;
  elementInteractionsOptions?: {elementInteractionsCssSelectorAllowlist?: string; elementInteractionsActionClickAllowlist?: string; elementInteractionsPageUrlAllowlistString?: string; elementInteractionsPageUrlAllowlistRegex?: string; elementInteractionsDataAttributePrefixString?: string; elementInteractionsDataAttributePrefixRegex?: string};
  elementInteractionsCssSelectorAllowlist?: string;
  elementInteractionsActionClickAllowlist?: string;
  elementInteractionsPageUrlAllowlistString?: string;
  elementInteractionsPageUrlAllowlistRegex?: string;
  elementInteractionsDataAttributePrefixString?: string;
  elementInteractionsDataAttributePrefixRegex?: string;
  autocaptureFrustrationInteractions?: boolean;
  frustrationInteractionsOptions?: {rageClicksCssSelectorAllowlist?: string; deadClicksCssSelectorAllowlist?: string};
  rageClicksCssSelectorAllowlist?: string;
  deadClicksCssSelectorAllowlist?: string;
  autocaptureNetworkTracking?: boolean;
  networkTrackingIgnoreAmplitudeRequests?: boolean;
  networkTrackingIgnoreHosts?: string;
  networkTrackingCaptureRules?: Array<{urls?: string; methods?: string; statusCodeRange?: string; urlsRegex?: string}>;
  euData?: boolean;
  initUserId?: string;
  initOptions?: 'manual';
  initManualOptions?: Array<{key: 'flushIntervalMillis' | 'flushMaxRetries' | 'flushQueueSize' | 'logLevel' | 'minIdLength' | 'serverUrl' | 'useBatch' | 'appVersion' | 'deviceId' | 'identityStorage' | 'partnerId' | 'sessionTimeout' | 'userId' | 'optOut' | 'transport'; value: string}>;
  initTrackingOptions?: Array<{key: 'ipAddress' | 'language' | 'platform'; value: string}>;
  initCookieOptions?: Array<{key: 'domain' | 'expiration' | 'sameSite' | 'secure' | 'upgrade'; value: string}>;
  userAgentEnrichment?: boolean;
  userAgentEnrichmentOptions?: {osName?: boolean; osVersion?: boolean; deviceManufacturer?: boolean; deviceModel?: boolean};
  osName?: boolean;
  osVersion?: boolean;
  deviceManufacturer?: boolean;
  deviceModel?: boolean;
  sessionReplay?: boolean;
  guidesSurveys?: boolean;
  advanced?: {instanceName?: string};
  instanceName?: string;
}