# Creates jira tickets for new github issues to help triage
name: Jira Issue Creator For GTM template

on:
  issues:
    types: [opened]
  workflow_call:
    inputs:
      label:
        type: string

jobs:
  call-workflow-passing-data:
    uses: amplitude/amplitude-browser-sdk-gtm-template/.github/workflows/jira-issue-create-template.yml@main
    with:
      label: "gtm-client-ts-template"
      subcomponent: "dx_gtm_client_ts_template"
    secrets:
      JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      JIRA_PROJECT: ${{ secrets.JIRA_PROJECT }}